elec <- read.table("household_power_consumption.txt",sep = ';',header=TRUE)
elec <- elec[elec$Date %in% c("1/2/2007","2/2/2007"),]
elec$Time1 <- as.character(elec$Time)
elec$DateTime <- as.POSIXct(paste(elec$Date, elec$Time1), format="%d/%m/%Y %H:%M:%S")
png("plot3.png",width=480,height=480)
plot(elec$DateTime, as.numeric(as.character(elec$Sub_metering_1)),type="n",xlab="",ylab="Energy sub metering",main="")
lines(elec$DateTime, as.numeric(as.character(elec$Sub_metering_1)),type="l",col="black")
lines(elec$DateTime, as.numeric(as.character(elec$Sub_metering_2)),type="l",col="red")
lines(elec$DateTime, as.numeric(as.character(elec$Sub_metering_3)),type="l",col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1)
dev.off()
