elec <- read.table("household_power_consumption.txt",sep = ';',header=TRUE)
elec <- elec[elec$Date %in% c("1/2/2007","2/2/2007"),]
elec$Time1 <- as.character(elec$Time)
elec$DateTime <- as.POSIXct(paste(elec$Date, elec$Time1), format="%d/%m/%Y %H:%M:%S")
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(elec$DateTime, as.numeric(as.character(elec$Global_active_power)),type="l",ylab="Global Active Power",main="",xlab="")
plot(elec$DateTime, as.numeric(as.character(elec$Voltage)),type="l",ylab="Voltage",main="",xlab="datetime")
plot(elec$DateTime, as.numeric(as.character(elec$Sub_metering_1)),type="n",ylab="Energy sub metering",xlab="",main="")
lines(elec$DateTime, as.numeric(as.character(elec$Sub_metering_1)),type="l",col="black")
lines(elec$DateTime, as.numeric(as.character(elec$Sub_metering_2)),type="l",col="red")
lines(elec$DateTime, as.numeric(as.character(elec$Sub_metering_3)),type="l",col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1)
plot(elec$DateTime, as.numeric(as.character(elec$Global_reactive_power)),type="l",ylab="Global_reactive_power",xlab="datetime",main="")
dev.off()

